param(
  [string]$AlpacaKeyId,
  [string]$AlpacaSecretKey,
  [string]$TradingWebhookUrl,
  [string]$TradeWebhookUrl,
  [string]$BotWebhookUrl,
  [ValidateSet('safe', 'active', 'turbo')]
  [string]$Autostart = 'safe',
  [string]$DataFeed = 'iex',
  [switch]$EnableCrypto,
  [ValidateSet('alpaca', 'binance')]
  [string]$CryptoVenue = 'alpaca'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$envPath = Join-Path $root '.env.local'

function Ask($label, $current = '') {
  if ($current) { return $current }
  return Read-Host $label
}

function Validate-DiscordWebhook($name, $value) {
  if (-not $value) { return }
  if ($value -notmatch '^https://([^/]+\.)?discord\.com/api/webhooks/') {
    throw "$name must be an HTTPS discord.com webhook URL."
  }
}

$AlpacaKeyId = Ask 'Alpaca paper API key id' $AlpacaKeyId
$AlpacaSecretKey = Ask 'Alpaca paper API secret key' $AlpacaSecretKey
$TradingWebhookUrl = Ask 'Discord radar/status webhook URL (blank to disable)' $TradingWebhookUrl
$TradeWebhookUrl = Ask 'Discord bot-trade webhook URL (blank to disable)' $TradeWebhookUrl
$BotWebhookUrl = Ask 'Discord bot-watch/vitals webhook URL (blank to use bot-trade webhook)' $BotWebhookUrl

Validate-DiscordWebhook 'DISCORD_TRADING_WEBHOOK_URL' $TradingWebhookUrl
Validate-DiscordWebhook 'DISCORD_TRADE_WEBHOOK_URL' $TradeWebhookUrl
Validate-DiscordWebhook 'DISCORD_BOT_WEBHOOK_URL' $BotWebhookUrl

$values = [ordered]@{
  ALPACA_API_KEY_ID = $AlpacaKeyId
  ALPACA_API_SECRET_KEY = $AlpacaSecretKey
  ALPACA_DATA_FEED = $DataFeed
  ALPACA_TRADING_BASE_URL = 'https://paper-api.alpaca.markets'
  PAPER_BOT_AUTOSTART = $Autostart
  PAPER_BOT_KEEP_AWAKE = 'true'
  PAPER_BOT_COST_MODEL = 'true'
  PAPER_BOT_STOCK_SLIPPAGE_BPS = '3'
  PAPER_BOT_CRYPTO_SLIPPAGE_BPS = '5'
  PAPER_BOT_STOCK_FEE_BPS = '0'
  PAPER_BOT_CRYPTO_FEE_BPS = '25'
  PAPER_BOT_MAKER_SHADOW = 'true'
  DISCORD_TRADING_WEBHOOK_URL = $TradingWebhookUrl
  DISCORD_TRADE_WEBHOOK_URL = $TradeWebhookUrl
  DISCORD_BOT_WEBHOOK_URL = $(if ($BotWebhookUrl) { $BotWebhookUrl } else { $TradeWebhookUrl })
  DISCORD_BOT_STATUS_INTERVAL_MINUTES = '3'
  DISCORD_BOT_STATUS_EDIT_WINDOW_MINUTES = '360'
  PAPER_BOT_ANALYZER_AUTOSTART = 'true'
  PAPER_BOT_ANALYZER_INTERVAL_SECONDS = '60'
  PAPER_BOT_ANALYZER_MIN_TRADES = '100'
  PAPER_BOT_ENFORCE_DAILY_RISK_GUARD = 'true'
  PAPER_BOT_MACRO_BLACKOUT = 'true'
  PAPER_BOT_MACRO_BLACKOUT_PRE_MIN = '2'
  PAPER_BOT_MACRO_BLACKOUT_POST_MIN = '10'
  BOT_ENABLE_CRYPTO = $(if ($EnableCrypto) { 'true' } else { 'false' })
  BOT_CRYPTO_VENUE = $CryptoVenue
  PAPER_BOT_BINANCE_TAKER_FEE_BPS = '10'
  BINANCE_TESTNET_API_KEY = ''
  BINANCE_TESTNET_API_SECRET = ''
  BINANCE_TESTNET_BASE_URL = 'https://testnet.binance.vision'
}

$lines = @(
  '# Local paper-bot secrets/config. This file is intentionally git-ignored.'
  '# Generated by scripts/setup-paper-bot-env.ps1.'
)
foreach ($pair in $values.GetEnumerator()) {
  $lines += "$($pair.Key)=$($pair.Value)"
}

Set-Content -Path $envPath -Value $lines -Encoding UTF8

$acl = Get-Acl -LiteralPath $envPath
$acl.SetAccessRuleProtection($true, $false)
$rights = [Security.AccessControl.FileSystemRights]::FullControl
$inheritance = [Security.AccessControl.InheritanceFlags]::None
$propagation = [Security.AccessControl.PropagationFlags]::None
$allow = [Security.AccessControl.AccessControlType]::Allow
$principals = @(
  [Security.Principal.WindowsIdentity]::GetCurrent().Name,
  'BUILTIN\Administrators',
  'NT AUTHORITY\SYSTEM'
)
foreach ($principal in $principals) {
  $rule = [Security.AccessControl.FileSystemAccessRule]::new($principal, $rights, $inheritance, $propagation, $allow)
  $acl.AddAccessRule($rule) | Out-Null
}
Set-Acl -LiteralPath $envPath -AclObject $acl

Write-Host "Wrote $envPath"
Write-Host 'Restricted .env.local permissions to the current account, Administrators, and SYSTEM.'
Write-Host 'Start or restart with: npm run dev:forever'
